[package]
name = "lemon3d"
version = "0.0.1"
authors = [ "Jingkai Mao <oammix@gmail.com>" ]

[dependencies]
bit-set = "*"
lazy_static = "*"
deque = "*"
rand = "*"
libc = "*"
zip = "*"
json = "*"
glutin = "*"
gl = "*"
cgmath = "*"
serde = "*"
serde_derive = "*"
serde_json = "*"
bincode = "1.0.0-alpha2"