[package]
name = "crayon-cli"
version = "0.0.5"
authors = ["Jingkai Mao <oammix@gmail.com>"]
build = "build.rs"

[dependencies]
crayon = { path = "../crayon-runtime" }
crayon_workflow = { path = "../crayon-workflow" }
error-chain = "0.11.0"
clap = "2.26.2"

[build-dependencies]