[package]
name = "crayon-canvas"
version = "0.0.6"
authors = ["Jingkai Mao <oammix@gmail.com>"]

[dependencies]
crayon = { path = "../../" }
lazy_static = "1.0.0"
error-chain = "0.11.0"

rusttype = "0.3.0"
unicode-normalization = "0.1.5"

[dev-dependencies]
rand = "0.3.18"