[package]
name = "crayon-cli"
version = "0.0.2"
authors = ["Jingkai Mao <oammix@gmail.com>"]
build = "build.rs"

[dependencies]
error-chain = "0.10.0"
clap = "2.25.1"
toml = "0.4"

[build-dependencies]